module.exports = {
  SERVER_STATUS: {
    RUNNING: 'RUNNING',
    STOPPED: 'STOPPED',
    BROKEN: 'BROKEN',
    INSTALLING: 'INSTALLING'
  },
  TRANSACTION_TYPES: {
    SERVER_CREATE: 'SERVER_CREATE',
    SERVER_RENEW: 'SERVER_RENEW',
    DAILY_REWARD: 'DAILY_REWARD',
    REFERRAL_BONUS: 'REFERRAL_BONUS',
    SERVER_DELETE_REFUND: 'SERVER_DELETE_REFUND',
    ADMIN_ADJUST: 'ADMIN_ADJUST'
  },
  ECONOMY: {
    INITIAL_BALANCE: 100,
    SERVER_COST: 100,
    SERVER_DURATION_DAYS: 10,
    DAILY_REWARD: 10,
    REFERRAL_BONUS: 15,
    DAILY_COOLDOWN_HOURS: 24
  },
  LIMITS: {
    MAX_SERVERS_PER_USER: 5,
    MAX_ENV_VARS_PER_SERVER: 40,
    MAX_ENV_VALUE_LENGTH: 4000,
    MAX_SINGLE_FILE_BYTES: 256 * 1024,
    MAX_TOTAL_FILES_BYTES: 2 * 1024 * 1024,
    TRANSACTION_RETENTION_DAYS: 180,
    EXPIRED_SERVER_GRACE_DAYS: 7,
    MAINTENANCE_INTERVAL_MS: 6 * 60 * 60 * 1000
  }
};